name: buapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Supabase
  supabase_flutter: ^2.3.4
  
  # Firebase
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.6.5
  firebase_messaging: ^14.7.15
  firebase_analytics: ^10.8.5
  firebase_crashlytics: ^3.4.14
  
  # UI
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  google_fonts: ^6.1.0
  flutter_spinkit: ^5.2.0
  
  # Utils
  image_picker: ^1.0.7
  intl: ^0.19.0
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2
  http: ^1.2.0
  path_provider: ^2.1.2
  
  # State Management
  provider: ^6.1.1
  flutter_bloc: ^8.1.3
  
  # Connectivity
  connectivity_plus: ^5.0.2
  
  # Animations
  lottie: ^3.0.0

  logging: ^1.0.2
  
  # Charts and data visualization
  fl_chart: ^0.66.2
  
  # Local notifications
  flutter_local_notifications: ^19.0.0
  timezone: ^0.10.0
  
  # PDF viewing and generation
  pdf: ^3.10.7
  printing: ^5.11.1
  
  # QR code
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

